"use client"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button";import { Input } from "@/components/ui/input";import { Textarea } from "@/components/ui/textarea"
import { createJob, getAdminJob, updateJob } from "../../services/jobService";import { getErrorMessage } from "../../services/api";import { ErrorBox, PageHeader, panel } from "../components"
export default function JobForm({id}:{id?:string}){const router=useRouter(),[data,setData]=useState<any>({title:"",slug:"",location:"",category:"",bullets:"",note:"",application_email:"",application_url:"",status:"draft"}),[error,setError]=useState(""),[saving,setSaving]=useState(false)
useEffect(()=>{if(id)getAdminJob(id).then(x=>setData({...x,bullets:x.bullets.join("\n")})).catch(e=>setError(getErrorMessage(e)))},[id])
const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const f=new FormData();["title","slug","location","category","note","application_email","application_url","status"].forEach(k=>data[k]&&f.append(k,data[k]));data.bullets.split("\n").filter(Boolean).forEach((v:string)=>f.append("bullets[]",v));const image=(e.currentTarget as HTMLFormElement).elements.namedItem("image") as HTMLInputElement;if(image.files?.[0])f.append("image",image.files[0]);id?await updateJob(id,f):await createJob(f);router.push("/dashboard/website/jobs")}catch(e){setError(getErrorMessage(e))}finally{setSaving(false)}}
return <><PageHeader title={id?"Edit job":"Add new job"} description="Job details displayed on the public careers page."/><form onSubmit={submit} className={`${panel} max-w-3xl space-y-5 p-6`}>{error&&<ErrorBox message={error}/>}<div className="grid gap-4 md:grid-cols-2">{["title","slug","location","category","application_email","application_url"].map(k=><label key={k} className="text-sm capitalize">{k.replace("_"," ")}<Input required={["title","location","category"].includes(k)} value={data[k]||""} onChange={e=>setData({...data,[k]:e.target.value})} className="mt-1 border-slate-600 bg-slate-900"/></label>)}</div><label className="block text-sm">Bullet points (one per line)<Textarea value={data.bullets} onChange={e=>setData({...data,bullets:e.target.value})} className="mt-1 min-h-32 border-slate-600 bg-slate-900"/></label><label className="block text-sm">Note<Textarea value={data.note||""} onChange={e=>setData({...data,note:e.target.value})} className="mt-1 border-slate-600 bg-slate-900"/></label><div className="grid gap-4 md:grid-cols-2"><label className="text-sm">Status<select value={data.status} onChange={e=>setData({...data,status:e.target.value})} className="mt-1 block w-full rounded-md border border-slate-600 bg-slate-900 p-2"><option>draft</option><option>published</option><option>closed</option><option>archived</option></select></label><label className="text-sm">Image<Input name="image" type="file" accept="image/*" className="mt-1 border-slate-600 bg-slate-900"/></label></div><Button disabled={saving}>{saving?"Saving...":"Save job"}</Button></form></>}
